### ISSUE TITLE
Review Comments

### ISSUE THREAD

**Issue by raghuprathap** [mnaresh2012/react-chat-kit#1]
Direct messaging happening but not group messaging or room messaging
Logout option required.
Creating public/private room feature need to be there.

State management handled using react component built in state but not redux, react-redux, redux-saga.
Test cases are missing.

**Comment by mnaresh2012** [comment]
Hi @raghuprathap, i have taken care of all the above scenario. I have share the new repo link in slack and updated  the google-sheet as-well. please check. Thanks.
